	Computer_System u0 (
		.done_sram_s1_address            (<connected-to-done_sram_s1_address>),            //         done_sram_s1.address
		.done_sram_s1_clken              (<connected-to-done_sram_s1_clken>),              //                     .clken
		.done_sram_s1_chipselect         (<connected-to-done_sram_s1_chipselect>),         //                     .chipselect
		.done_sram_s1_write              (<connected-to-done_sram_s1_write>),              //                     .write
		.done_sram_s1_readdata           (<connected-to-done_sram_s1_readdata>),           //                     .readdata
		.done_sram_s1_writedata          (<connected-to-done_sram_s1_writedata>),          //                     .writedata
		.hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>), //               hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),   //                     .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),   //                     .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),   //                     .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),   //                     .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),   //                     .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),   //                     .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_io_hps_io_emac1_inst_MDC>),    //                     .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>), //                     .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>), //                     .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>), //                     .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),   //                     .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),   //                     .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),   //                     .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0     (<connected-to-hps_io_hps_io_qspi_inst_IO0>),     //                     .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1     (<connected-to-hps_io_hps_io_qspi_inst_IO1>),     //                     .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2     (<connected-to-hps_io_hps_io_qspi_inst_IO2>),     //                     .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3     (<connected-to-hps_io_hps_io_qspi_inst_IO3>),     //                     .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0     (<connected-to-hps_io_hps_io_qspi_inst_SS0>),     //                     .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK     (<connected-to-hps_io_hps_io_qspi_inst_CLK>),     //                     .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_io_hps_io_sdio_inst_CMD>),     //                     .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_io_hps_io_sdio_inst_D0>),      //                     .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_io_hps_io_sdio_inst_D1>),      //                     .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_io_hps_io_sdio_inst_CLK>),     //                     .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_io_hps_io_sdio_inst_D2>),      //                     .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_io_hps_io_sdio_inst_D3>),      //                     .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_io_hps_io_usb1_inst_D0>),      //                     .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_io_hps_io_usb1_inst_D1>),      //                     .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_io_hps_io_usb1_inst_D2>),      //                     .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_io_hps_io_usb1_inst_D3>),      //                     .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_io_hps_io_usb1_inst_D4>),      //                     .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_io_hps_io_usb1_inst_D5>),      //                     .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_io_hps_io_usb1_inst_D6>),      //                     .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_io_hps_io_usb1_inst_D7>),      //                     .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_io_hps_io_usb1_inst_CLK>),     //                     .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_io_hps_io_usb1_inst_STP>),     //                     .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_io_hps_io_usb1_inst_DIR>),     //                     .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_io_hps_io_usb1_inst_NXT>),     //                     .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK    (<connected-to-hps_io_hps_io_spim1_inst_CLK>),    //                     .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI   (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),   //                     .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO   (<connected-to-hps_io_hps_io_spim1_inst_MISO>),   //                     .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0    (<connected-to-hps_io_hps_io_spim1_inst_SS0>),    //                     .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_io_hps_io_uart0_inst_RX>),     //                     .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_io_hps_io_uart0_inst_TX>),     //                     .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),     //                     .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),     //                     .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),     //                     .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),     //                     .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),  //                     .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),  //                     .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),  //                     .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO41  (<connected-to-hps_io_hps_io_gpio_inst_GPIO41>),  //                     .hps_io_gpio_inst_GPIO41
		.hps_io_hps_io_gpio_inst_GPIO48  (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),  //                     .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),  //                     .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),  //                     .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),  //                     .hps_io_gpio_inst_GPIO61
		.inst_sram_s1_address            (<connected-to-inst_sram_s1_address>),            //         inst_sram_s1.address
		.inst_sram_s1_clken              (<connected-to-inst_sram_s1_clken>),              //                     .clken
		.inst_sram_s1_chipselect         (<connected-to-inst_sram_s1_chipselect>),         //                     .chipselect
		.inst_sram_s1_write              (<connected-to-inst_sram_s1_write>),              //                     .write
		.inst_sram_s1_readdata           (<connected-to-inst_sram_s1_readdata>),           //                     .readdata
		.inst_sram_s1_writedata          (<connected-to-inst_sram_s1_writedata>),          //                     .writedata
		.inst_sram_s1_byteenable         (<connected-to-inst_sram_s1_byteenable>),         //                     .byteenable
		.memory_mem_a                    (<connected-to-memory_mem_a>),                    //               memory.mem_a
		.memory_mem_ba                   (<connected-to-memory_mem_ba>),                   //                     .mem_ba
		.memory_mem_ck                   (<connected-to-memory_mem_ck>),                   //                     .mem_ck
		.memory_mem_ck_n                 (<connected-to-memory_mem_ck_n>),                 //                     .mem_ck_n
		.memory_mem_cke                  (<connected-to-memory_mem_cke>),                  //                     .mem_cke
		.memory_mem_cs_n                 (<connected-to-memory_mem_cs_n>),                 //                     .mem_cs_n
		.memory_mem_ras_n                (<connected-to-memory_mem_ras_n>),                //                     .mem_ras_n
		.memory_mem_cas_n                (<connected-to-memory_mem_cas_n>),                //                     .mem_cas_n
		.memory_mem_we_n                 (<connected-to-memory_mem_we_n>),                 //                     .mem_we_n
		.memory_mem_reset_n              (<connected-to-memory_mem_reset_n>),              //                     .mem_reset_n
		.memory_mem_dq                   (<connected-to-memory_mem_dq>),                   //                     .mem_dq
		.memory_mem_dqs                  (<connected-to-memory_mem_dqs>),                  //                     .mem_dqs
		.memory_mem_dqs_n                (<connected-to-memory_mem_dqs_n>),                //                     .mem_dqs_n
		.memory_mem_odt                  (<connected-to-memory_mem_odt>),                  //                     .mem_odt
		.memory_mem_dm                   (<connected-to-memory_mem_dm>),                   //                     .mem_dm
		.memory_oct_rzqin                (<connected-to-memory_oct_rzqin>),                //                     .oct_rzqin
		.pll_0_refclk_clk                (<connected-to-pll_0_refclk_clk>),                //         pll_0_refclk.clk
		.pll_0_reset_reset               (<connected-to-pll_0_reset_reset>),               //          pll_0_reset.reset
		.sdram_clk_clk                   (<connected-to-sdram_clk_clk>),                   //            sdram_clk.clk
		.sram_0_s1_address               (<connected-to-sram_0_s1_address>),               //            sram_0_s1.address
		.sram_0_s1_clken                 (<connected-to-sram_0_s1_clken>),                 //                     .clken
		.sram_0_s1_chipselect            (<connected-to-sram_0_s1_chipselect>),            //                     .chipselect
		.sram_0_s1_write                 (<connected-to-sram_0_s1_write>),                 //                     .write
		.sram_0_s1_readdata              (<connected-to-sram_0_s1_readdata>),              //                     .readdata
		.sram_0_s1_writedata             (<connected-to-sram_0_s1_writedata>),             //                     .writedata
		.sram_0_s1_byteenable            (<connected-to-sram_0_s1_byteenable>),            //                     .byteenable
		.sram_10_s1_address              (<connected-to-sram_10_s1_address>),              //           sram_10_s1.address
		.sram_10_s1_clken                (<connected-to-sram_10_s1_clken>),                //                     .clken
		.sram_10_s1_chipselect           (<connected-to-sram_10_s1_chipselect>),           //                     .chipselect
		.sram_10_s1_write                (<connected-to-sram_10_s1_write>),                //                     .write
		.sram_10_s1_readdata             (<connected-to-sram_10_s1_readdata>),             //                     .readdata
		.sram_10_s1_writedata            (<connected-to-sram_10_s1_writedata>),            //                     .writedata
		.sram_10_s1_byteenable           (<connected-to-sram_10_s1_byteenable>),           //                     .byteenable
		.sram_11_s1_address              (<connected-to-sram_11_s1_address>),              //           sram_11_s1.address
		.sram_11_s1_clken                (<connected-to-sram_11_s1_clken>),                //                     .clken
		.sram_11_s1_chipselect           (<connected-to-sram_11_s1_chipselect>),           //                     .chipselect
		.sram_11_s1_write                (<connected-to-sram_11_s1_write>),                //                     .write
		.sram_11_s1_readdata             (<connected-to-sram_11_s1_readdata>),             //                     .readdata
		.sram_11_s1_writedata            (<connected-to-sram_11_s1_writedata>),            //                     .writedata
		.sram_11_s1_byteenable           (<connected-to-sram_11_s1_byteenable>),           //                     .byteenable
		.sram_1_s1_address               (<connected-to-sram_1_s1_address>),               //            sram_1_s1.address
		.sram_1_s1_clken                 (<connected-to-sram_1_s1_clken>),                 //                     .clken
		.sram_1_s1_chipselect            (<connected-to-sram_1_s1_chipselect>),            //                     .chipselect
		.sram_1_s1_write                 (<connected-to-sram_1_s1_write>),                 //                     .write
		.sram_1_s1_readdata              (<connected-to-sram_1_s1_readdata>),              //                     .readdata
		.sram_1_s1_writedata             (<connected-to-sram_1_s1_writedata>),             //                     .writedata
		.sram_1_s1_byteenable            (<connected-to-sram_1_s1_byteenable>),            //                     .byteenable
		.sram_2_s1_address               (<connected-to-sram_2_s1_address>),               //            sram_2_s1.address
		.sram_2_s1_clken                 (<connected-to-sram_2_s1_clken>),                 //                     .clken
		.sram_2_s1_chipselect            (<connected-to-sram_2_s1_chipselect>),            //                     .chipselect
		.sram_2_s1_write                 (<connected-to-sram_2_s1_write>),                 //                     .write
		.sram_2_s1_readdata              (<connected-to-sram_2_s1_readdata>),              //                     .readdata
		.sram_2_s1_writedata             (<connected-to-sram_2_s1_writedata>),             //                     .writedata
		.sram_2_s1_byteenable            (<connected-to-sram_2_s1_byteenable>),            //                     .byteenable
		.sram_3_s1_address               (<connected-to-sram_3_s1_address>),               //            sram_3_s1.address
		.sram_3_s1_clken                 (<connected-to-sram_3_s1_clken>),                 //                     .clken
		.sram_3_s1_chipselect            (<connected-to-sram_3_s1_chipselect>),            //                     .chipselect
		.sram_3_s1_write                 (<connected-to-sram_3_s1_write>),                 //                     .write
		.sram_3_s1_readdata              (<connected-to-sram_3_s1_readdata>),              //                     .readdata
		.sram_3_s1_writedata             (<connected-to-sram_3_s1_writedata>),             //                     .writedata
		.sram_3_s1_byteenable            (<connected-to-sram_3_s1_byteenable>),            //                     .byteenable
		.sram_4_s1_address               (<connected-to-sram_4_s1_address>),               //            sram_4_s1.address
		.sram_4_s1_clken                 (<connected-to-sram_4_s1_clken>),                 //                     .clken
		.sram_4_s1_chipselect            (<connected-to-sram_4_s1_chipselect>),            //                     .chipselect
		.sram_4_s1_write                 (<connected-to-sram_4_s1_write>),                 //                     .write
		.sram_4_s1_readdata              (<connected-to-sram_4_s1_readdata>),              //                     .readdata
		.sram_4_s1_writedata             (<connected-to-sram_4_s1_writedata>),             //                     .writedata
		.sram_4_s1_byteenable            (<connected-to-sram_4_s1_byteenable>),            //                     .byteenable
		.sram_5_s1_address               (<connected-to-sram_5_s1_address>),               //            sram_5_s1.address
		.sram_5_s1_clken                 (<connected-to-sram_5_s1_clken>),                 //                     .clken
		.sram_5_s1_chipselect            (<connected-to-sram_5_s1_chipselect>),            //                     .chipselect
		.sram_5_s1_write                 (<connected-to-sram_5_s1_write>),                 //                     .write
		.sram_5_s1_readdata              (<connected-to-sram_5_s1_readdata>),              //                     .readdata
		.sram_5_s1_writedata             (<connected-to-sram_5_s1_writedata>),             //                     .writedata
		.sram_5_s1_byteenable            (<connected-to-sram_5_s1_byteenable>),            //                     .byteenable
		.sram_6_s1_address               (<connected-to-sram_6_s1_address>),               //            sram_6_s1.address
		.sram_6_s1_clken                 (<connected-to-sram_6_s1_clken>),                 //                     .clken
		.sram_6_s1_chipselect            (<connected-to-sram_6_s1_chipselect>),            //                     .chipselect
		.sram_6_s1_write                 (<connected-to-sram_6_s1_write>),                 //                     .write
		.sram_6_s1_readdata              (<connected-to-sram_6_s1_readdata>),              //                     .readdata
		.sram_6_s1_writedata             (<connected-to-sram_6_s1_writedata>),             //                     .writedata
		.sram_6_s1_byteenable            (<connected-to-sram_6_s1_byteenable>),            //                     .byteenable
		.sram_7_s1_address               (<connected-to-sram_7_s1_address>),               //            sram_7_s1.address
		.sram_7_s1_clken                 (<connected-to-sram_7_s1_clken>),                 //                     .clken
		.sram_7_s1_chipselect            (<connected-to-sram_7_s1_chipselect>),            //                     .chipselect
		.sram_7_s1_write                 (<connected-to-sram_7_s1_write>),                 //                     .write
		.sram_7_s1_readdata              (<connected-to-sram_7_s1_readdata>),              //                     .readdata
		.sram_7_s1_writedata             (<connected-to-sram_7_s1_writedata>),             //                     .writedata
		.sram_7_s1_byteenable            (<connected-to-sram_7_s1_byteenable>),            //                     .byteenable
		.sram_8_s1_address               (<connected-to-sram_8_s1_address>),               //            sram_8_s1.address
		.sram_8_s1_clken                 (<connected-to-sram_8_s1_clken>),                 //                     .clken
		.sram_8_s1_chipselect            (<connected-to-sram_8_s1_chipselect>),            //                     .chipselect
		.sram_8_s1_write                 (<connected-to-sram_8_s1_write>),                 //                     .write
		.sram_8_s1_readdata              (<connected-to-sram_8_s1_readdata>),              //                     .readdata
		.sram_8_s1_writedata             (<connected-to-sram_8_s1_writedata>),             //                     .writedata
		.sram_8_s1_byteenable            (<connected-to-sram_8_s1_byteenable>),            //                     .byteenable
		.sram_9_s1_address               (<connected-to-sram_9_s1_address>),               //            sram_9_s1.address
		.sram_9_s1_clken                 (<connected-to-sram_9_s1_clken>),                 //                     .clken
		.sram_9_s1_chipselect            (<connected-to-sram_9_s1_chipselect>),            //                     .chipselect
		.sram_9_s1_write                 (<connected-to-sram_9_s1_write>),                 //                     .write
		.sram_9_s1_readdata              (<connected-to-sram_9_s1_readdata>),              //                     .readdata
		.sram_9_s1_writedata             (<connected-to-sram_9_s1_writedata>),             //                     .writedata
		.sram_9_s1_byteenable            (<connected-to-sram_9_s1_byteenable>),            //                     .byteenable
		.system_pll_ref_clk_clk          (<connected-to-system_pll_ref_clk_clk>),          //   system_pll_ref_clk.clk
		.system_pll_ref_reset_reset      (<connected-to-system_pll_ref_reset_reset>)       // system_pll_ref_reset.reset
	);

